### ISSUE TITLE
DSA parameters generation issue with newer openssl

### ISSUE THREAD

**Issue by mrc0mmand** [redhat-qe-security/certgen#2]
Newer versions of openssl require that `numbits` in `openssl dsaparam` must be the last argument.

Affected code: [lib.sh:634](https://github.com/redhat-qe-security/certgen/blob/master/certgen/lib.sh#L634)
Affected version: OpenSSL 1.1.1-dev and OpenSSL 1.1.0f-dev

Excerpt from the newer manpage (dsaparam(1)):
```
numbits
    This option specifies that a parameter set should be generated of size numbits. It must be the last option. If this option is included then the input file (if
    any) is ignored.
```

Actual results:
```
# openssl dsaparam 1024 -out testparam.pem <<< ""
unable to load DSA parameters
140691007125312:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:691:Expecting: DSA PARAMETERS
```

Expected results:
```
# openssl dsaparam -out testparam.pem 1024 <<< ""
Generating DSA parameters, 1024 bit long prime
This could take some time
.+.+++++++++++++++++++++++++++++++++++++++++++++++++++*
...
# echo $?
0
```

**Comment by tomato42** [comment]
known issue, but the fix I have depends on few other patches so I need to re-synchronise the repos

**Comment by tomato42** [comment]
could you retry current master? I think 8b3cd2ef79 should have fixed it
